
const Blogs = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus, aut recusandae commodi quae expedita tenetur iste vel necessitatibus inventore, eligendi ullam sint illo ipsum amet quos illum. Cupiditate maxime quisquam eum suscipit, vel modi cum, repudiandae expedita quia necessitatibus cumque ducimus, quaerat unde ex laudantium reiciendis provident similique voluptatibus. Nesciunt ipsum excepturi ut! Deleniti nulla possimus eos? Cum, dolor perferendis? Veniam quis eos magni corrupti tenetur animi deserunt maxime, esse itaque pariatur, dolore reiciendis ipsum sint temporibus earum tempora provident consequatur nemo corporis accusantium et ipsam soluta modi. Totam cum eaque beatae dignissimos ipsa laboriosam soluta id, repellendus illo. A, aut, sunt cum facere magni deleniti eius tenetur obcaecati commodi, explicabo dignissimos consequuntur? Alias accusamus atque est, laboriosam necessitatibus incidunt ipsam dicta vero voluptatibus nesciunt? Cumque numquam, aspernatur explicabo, quia inventore nesciunt reiciendis praesentium maxime suscipit dolorum ad illo, incidunt unde nobis officiis eaque. Ullam temporibus natus placeat animi deleniti at deserunt a quidem fugiat, quia modi perspiciatis. Molestiae alias consectetur ea dolorum non corporis reiciendis commodi, rem maxime impedit error velit a, ipsum, accusamus nam deserunt cumque quia officia optio eius at ducimus. Pariatur aliquid eveniet, rerum quasi fugiat modi maxime, placeat molestiae quaerat deserunt eum laudantium facilis officia fuga, ipsam temporibus quibusdam porro delectus culpa neque eaque debitis suscipit. Delectus quaerat maiores cum illo, perferendis magnam culpa, autem eius placeat veniam aspernatur quia minima repellendus dignissimos vero ratione obcaecati excepturi? Nam dolores, voluptas incidunt maxime, in harum voluptatum ex repudiandae iusto aliquam quidem hic iste quo. Ad illo voluptatem inventore laudantium asperiores, adipisci ab dolores recusandae necessitatibus, illum delectus dolor doloremque cupiditate? Doloribus ad fuga maiores. At veniam sit odit consequuntur cum nobis officiis incidunt ut soluta? Ducimus repellendus nulla accusantium, ratione tenetur ipsum facilis blanditiis aliquam perferendis necessitatibus corporis suscipit consequuntur ipsam, iste, repudiandae autem!</p>
        </div>
    );
};

export default Blogs;